version: '3.8'

services:
  db:
    restart: always
    container_name: db
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB-orders}
      POSTGRES_USER: ${POSTGRES_USER-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-password}

  django:
    restart: always
    container_name: django
    build:
      context: backend
    volumes:
      - ./backend:/app
    environment:
      DEBUG: ${DEBUG-True}
      SECRET_KEY: ${SECRET_KEY-replace_me}
      DATABASE_URL: ${DATABASE_URL-postgres://user:password@db:5432/orders}
    entrypoint:
      - ./entrypoint.sh
    ports:
      - "8080:8000"
    depends_on:
      - db

volumes:
  postgres_data: null
