# Generated by Django 4.1.1 on 2022-09-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "gsh_id",
                    models.PositiveIntegerField(verbose_name="№"),
                ),
                ("number", models.IntegerField(verbose_name="заказ №")),
                (
                    "usd_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        verbose_name="стоимость, $",
                    ),
                ),
                (
                    "rub_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="стоимость, ₽",
                    ),
                ),
                (
                    "delivery_date",
                    models.DateField(verbose_name="срок доставки"),
                ),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
            },
        ),
    ]
